language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

sudo: false

env:
  # avoid slow dependency resolution specifically for laravel 4.1
  - COMPOSER_REQS="laravel/framework:>=5.7"

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - vendor/bin/phpunit  --verbose
