language: php

php:
  - 7.2
  - 7.3

before_install:
  - sudo apt-get update
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
